#!/bin/bash

VUENGINE_HOME=$1
GAME_HOME=$2
VUENGINE_HEADER_FILES=`find $VUENGINE_HOME/source/ -name "*.h"`
GAME_HEADER_FILES=`find $GAME_HOME/source/  -name "*.h"`


CLASSES_FILE="classsFile.txt"
OUTPUT_C_FILE="$GAME_HOME/source/setupClasses.c"

rm -f $CLASSES_FILE
rm -f $OUTPUT_C_FILE
echo " " > $OUTPUT_C_FILE

echo "// Do not modify this file, it is autogenerated" > $OUTPUT_C_FILE

for header in $VUENGINE_HEADER_FILES; do
	className=`grep "__CLASS(" $header`
	className=`echo $className | sed 's/__CLASS(//' | sed 's/);//'`
	if ! [[ "$className" =~ "define" ]]; then
		if [ -n "$className" ]; then
			echo $className >> $CLASSES_FILE
		fi
	fi	
done

for header in $GAME_HEADER_FILES; do
	className=`grep "__CLASS(" $header`
	className=`echo $className | sed 's/__CLASS(//' | sed 's/);//'`
	if ! [[ "$className" =~ "define" ]]; then
		if [ -n "$className" ]; then
			echo $className >> $CLASSES_FILE
		fi
	fi	
done

CLASSES_NAMES=`cat $CLASSES_FILE`

echo " " >> $OUTPUT_C_FILE
echo "// includes" >> $OUTPUT_C_FILE

# Create the include directives
for className in $CLASSES_NAMES; do
	echo "#include <"$className".h>" >> $OUTPUT_C_FILE
done

echo " " >> $OUTPUT_C_FILE
echo "// setup function" >> $OUTPUT_C_FILE

#create the function
echo "void setupClasses(void)" >> $OUTPUT_C_FILE
echo "{" >> $OUTPUT_C_FILE

# Create the calls directives
for className in $CLASSES_NAMES; do
	echo "	"$className"_setVTable();" >> $OUTPUT_C_FILE
done
echo "}" >> $OUTPUT_C_FILE

rm -f $CLASSES_FILE