// Bundles the preprocessor into the committed dist/preprocessor.mjs that the
// makefiles invoke. Game developers never run this; only engine developers
// changing src/ do, via `npm install && npm run build`.
//
// The bundle targets QuickJS, which is what builds run: it is about a megabyte
// against Node's hundred, so VUEngine Studio can ship it and stay
// self-contained. The `.mjs` extension matters — it is how qjs knows to treat
// the file as a module.
//
// Node needs no bundle of its own. It runs the sources directly by stripping
// types (`node src/main.ts …`), which is what the tests rely on.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

await build({
	entryPoints: [join(here, 'src/main.ts')],
	outfile: join(here, 'dist/preprocessor.mjs'),
	bundle: true,
	format: 'esm',
	// QuickJS is not Node: it must not be given Node's builtins or resolution
	// conditions, and `os` and `std` are its own built-in modules, resolved at
	// run time rather than bundled.
	platform: 'neutral',
	target: 'es2020',
	external: ['os', 'std'],
	legalComments: 'none',
	logLevel: 'info',
	banner: {
		js: '// Generated by build.mjs from src/ — do not edit. See lib/compiler/preprocessor.js/readme.md.',
	},
	plugins: [
		{
			// Swap in the QuickJS host implementation. The checked-in default is
			// the Node one, so that the sources stay runnable under `node` and
			// `node --test`.
			name: 'platform',
			setup(pluginBuild) {
				pluginBuild.onResolve({ filter: /platform\.ts$/ }, () => ({
					path: join(here, 'src/platform/platform.quickjs.ts'),
				}));
			},
		},
	],
});
