#ifndef	DEBUG_CONFIG_H_
#undef	DEBUG_CONFIG_H_

#include <debugUtilities.h>

// avoid declaration warnings


// define / undefine as you see fit
//#define __PRINT_FRAMERATE
//#define __PRINT_DEBUG_ALERT
//#define __PROFILE_GAME
//#define __PROFILE_STREAMING
//#define __SHOW_GAME_PROFILING
//#define __SHOW_GAME_DETAILED_PROFILING
//#define __SHOW_GAME_PROFILE_DURING_TORN_FRAMES
//#define __SHOW_STREAMING_PROFILING
//#define __SHOW_SPRITES_PROFILING
//#define __DIMM_FOR_PROFILING
//#define __SHOW_TORN_FRAMES_COUNT
//#define __SHOW_VIP_OVERTIME_COUNT
//#define __DRAW_SHAPES
//#define __SHOW_PROCESS_NAME_DURING_FRAMESTART
//#define __SHOW_PROCESS_NAME_DURING_XPEND
//#define __SHOW_STACK_OVERFLOW_ALERT
//#define __SHOW_DETAILED_MEMORY_POOL_STATUS
//#define __SHOW_MEMORY_POOL_STATUS
//#define __SHOW_PHYSICS_PROFILING
//#define __SHOW_WIREFRAME_MANAGER_STATUS
//#define __SHOW_CAMERA_STATUS
//#define __SHOW_CHAR_MEMORY_STATUS
//#define __SHOW_SOUND_STATUS
//#define __REGISTER_LAST_PROCESS_NAME
//#define __FORCE_PRINTING_LAYER
//#define __FORCE_UPPERCASE
//#define __MAXIMUM_BOUNCINESS_COEFFICIENT		5.5f
//#define __FORCE_FONT "GuiTime"
//#define __DEFAUL_FONT "GuiTime"
//#define __MUTE_ALL_SOUND
//#define __DRAW_COMPLETE_BOXES
//#define __RUN_DELAYED_MESSAGES_DISPATCHING_AT_HALF_FRAME_RATE

//#undef __TIMER_RESOLUTION
//#define __TIMER_RESOLUTION						10


//#undef __SAFE_CAST
//#define __SAFE_CAST(ClassName, object) (ClassName)object
//#undef __CAMERA_MINIMUM_DISPLACEMENT_PIXELS_POWER
//#define __CAMERA_MINIMUM_DISPLACEMENT_PIXELS_POWER	1


// do not delete the following macros!

#ifdef __SHOW_PROCESS_NAME_DURING_FRAMESTART
#undef __REGISTER_PROCESS_NAME_DURING_FRAMESTART
#define __REGISTER_PROCESS_NAME_DURING_FRAMESTART
#endif

#ifdef __SHOW_PROCESS_NAME_DURING_XPEND
#undef __REGISTER_PROCESS_NAME_DURING_XPEND
#define __REGISTER_PROCESS_NAME_DURING_XPEND
#endif

#ifdef __REGISTER_PROCESS_NAME_DURING_FRAMESTART
#undef __REGISTER_LAST_PROCESS_NAME
#define __REGISTER_LAST_PROCESS_NAME
#endif

#ifdef __REGISTER_PROCESS_NAME_DURING_XPEND
#undef __REGISTER_LAST_PROCESS_NAME
#define __REGISTER_LAST_PROCESS_NAME
#endif

// show games's profiling during game
#ifdef __SHOW_GAME_DETAILED_PROFILING
#undef __PRINT_FRAMERATE
#undef __SHOW_GAME_PROFILING
#define __SHOW_GAME_PROFILING
#endif

#ifdef __SHOW_GAME_PROFILE_DURING_TORN_FRAMES
#undef __PROFILE_GAME
#define __PROFILE_GAME
#endif

// show games's profiling during game
#ifdef __SHOW_GAME_PROFILING
#undef __PROFILE_GAME
#define __PROFILE_GAME
#undef __DIMM_FOR_PROFILING
#define __DIMM_FOR_PROFILING
#endif

// show streaming's profiling during game
#ifdef __SHOW_STREAMING_PROFILING
#undef __PROFILE_GAME
#define __PROFILE_GAME
#undef __DIMM_FOR_PROFILING
#define __DIMM_FOR_PROFILING
#undef __PROFILE_STREAMING
#define __PROFILE_STREAMING
#endif

// show sprites's profiling during game
#ifdef __SHOW_SPRITES_PROFILING
#undef __PROFILE_GAME
#define __PROFILE_GAME
#undef __DIMM_FOR_PROFILING
#define __DIMM_FOR_PROFILING
#undef __FORCE_PRINTING_LAYER
#define __FORCE_PRINTING_LAYER
#endif

// enable game profiling when checking the VIP interrupt
#ifdef __PROFILE_GAME_STATE_DURING_VIP_INTERRUPT
#undef __PROFILE_GAME
#define __PROFILE_GAME
#undef __DIMM_FOR_PROFILING
#define __DIMM_FOR_PROFILING
#undef __FORCE_PRINTING_LAYER
#define __FORCE_PRINTING_LAYER
#endif

#ifdef __SHOW_DETAILED_MEMORY_POOL_STATUS
#undef __SHOW_MEMORY_POOL_STATUS
#define __SHOW_MEMORY_POOL_STATUS
#undef __DIMM_FOR_PROFILING
#define __DIMM_FOR_PROFILING
#undef __FORCE_PRINTING_LAYER
#define __FORCE_PRINTING_LAYER
#endif

#ifdef __SHOW_PHYSICS_PROFILING
#undef __FORCE_PRINTING_LAYER
#define __FORCE_PRINTING_LAYER
#endif

#ifdef __SHOW_STACK_OVERFLOW_ALERT
#undef __PRINT_PROFILING_INFO
#define __PRINT_PROFILING_INFO
#endif

#ifdef __PRINT_FRAMERATE
#ifndef __PRINT_PROFILING_INFO
#define __PRINT_PROFILING_INFO
#endif
#else
#ifdef __PROFILE_GAME
#ifndef __PRINT_PROFILING_INFO
#define __PRINT_PROFILING_INFO
#endif
#else
#ifdef __SHOW_MEMORY_POOL_STATUS
#ifndef __PRINT_PROFILING_INFO
#define __PRINT_PROFILING_INFO
#endif
#else
#ifdef __SHOW_STREAMING_PROFILING
#ifndef __PRINT_PROFILING_INFO
#define __PRINT_PROFILING_INFO
#endif
#endif
#endif
#endif
#endif

#ifdef __SHOW_GAME_PROFILING
#undef __TIMER_RESOLUTION
#define __TIMER_RESOLUTION						1
#endif

#endif
#undef __DIMM_FOR_PROFILING

#ifdef __PROFILE_GAME
#undef __REGISTER_LAST_PROCESS_NAME
#define __REGISTER_LAST_PROCESS_NAME
#undef __REGISTER_PROCESS_NAME_DURING_FRAMESTART
#define __REGISTER_PROCESS_NAME_DURING_FRAMESTART
#undef __REGISTER_PROCESS_NAME_DURING_XPEND
#define __REGISTER_PROCESS_NAME_DURING_XPEND
#endif
